name: "Pre-Integration"

on:
  push:
  workflow_dispatch:

env:
  VERSION: 1.1.0.${{ github.run_number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚙️ Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: 🧹 Clean
        run: dotnet clean -c Release && dotnet nuget locals all --clear

      - name: 🛠️ Building library in release mode
        run: dotnet pack -c Release -o packages -p:UseSourceLink=true -p:Version=${{ env.VERSION }} -p:PackageVersion=${{ env.VERSION }}

      - name: 🗳️ Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Packages
          path: |
            packages/*.nupkg
            README.md

  test:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: 🛒 Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: ⚙️ Setup dotnet 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: 🔁 Restore packages
        run: dotnet restore

      - name: 🧪 Run unit tests
        run: dotnet test -c Release